[project]
name = "bcping2"
version = "1.0.0"
description = "A minimalistic host status page built with Python and Flask"
dependencies = [
    "flask",
    "pythonping",
    "orjson"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"